---
title: "Shandong Inpatient Data Manipulation"
author: "Yao He"
date: "03/30/2021"
output:
  pdf_document: default
---
```{r, include = FALSE}
knitr::opts_chunk$set(message=FALSE)
knitr::opts_chunk$set(warning=FALSE)
options(scipen=999)

```

```{r,include=FALSE,message=FALSE,warning=FALSE}
# Load packages
library(knitr)
library(plyr)
library(readr)
library(dplyr) # mutate(), rename()
library(ggplot2)
library(lattice)
library(nlme)

#library(kableExtra)
#library(geepack)
#library(miceadds)
#library(data.table)
#library(doBy)
#library(tidyr)
#library(sandwich)
#library(lme4)
#library(UWbe536)
#library(MASS)
#library(lmtest)

```


```{r, echo=T}
# read in data OBSTETRICS
myfilesOB <- list.files(path="~/Documents/R/Research/Shandong/Data/OB/Use", pattern=".csv") #create a list of files in a specific folder

dfnameOB <- list() #create an empty list for the dataset names
for(i in myfilesOB){ #cycle thru all files in the list of files
    file_nameOB <- paste("~/Documents/R/Research/Shandong/Data/OB/Use/", i, sep="") #extract the original file name of the i-th file e.g. "OB204.csv"
    xOB <- read.csv(file_nameOB) #read in the dataset given the i-th file name and store as dataframe xOB
    assign(substr(i, 1, nchar(i)-4), xOB) #assign substringed file name from the 1st character to the last character before ".csv" to the df
    nameOB <- substr(i, 1, nchar(i)-4) #store the substringed df name
    dfnameOB[[nameOB]] <- xOB #store the df (i-th xOB) into the df list created earlier
}

# read in data GYNOCOLOGY
myfilesGYN <- list.files(path="~/Documents/R/Research/Shandong/Data/GYN/Use", pattern=".csv")

dfnameGYN <- list()
for(i in myfilesGYN){
    file_nameGYN <- paste("~/Documents/R/Research/Shandong/Data/GYN/Use/", i, sep="")
    xGYN <- read.csv(file_nameGYN)
    assign(substr(i, 1, nchar(i)-4), xGYN)
    nameGYN <- substr(i, 1, nchar(i)-4)
    dfnameGYN[[nameGYN]] <- xGYN 
}

# read in data PEDIATRICS
myfilesPED <- list.files(path="~/Documents/R/Research/Shandong/Data/PED", pattern=".csv")

dfnamePED <- list()
for(i in myfilesPED){
    file_namePED <- paste("~/Documents/R/Research/Shandong/Data/PED/", i, sep="")
    xPED <- read.csv(file_namePED)
    assign(substr(i, 1, nchar(i)-4), xPED)
    namePED <- substr(i, 1, nchar(i)-4)
    dfnamePED[[namePED]] <- xPED 
}

# read in data Ped. Surgery
myfilesPedSur <- list.files(path="~/Documents/R/Research/Shandong/Data/PedSur", pattern=".csv")

dfnamePedSur <- list()
for(i in myfilesPedSur){
    file_namePedSur <- paste("~/Documents/R/Research/Shandong/Data/PedSur/", i, sep="")
    xPedSur <- read.csv(file_namePedSur)
    assign(substr(i, 1, nchar(i)-4), xPedSur)
    namePedSur <- substr(i, 1, nchar(i)-4)
    dfnamePedSur[[namePedSur]] <- xPedSur
}

```

```{r, echo=T}
# consolidate all datasets across time in each category
datOB <- do.call(rbind, dfnameOB)
datGYN <- do.call(rbind, dfnameGYN)
datPED <- do.call(rbind, dfnamePED)
datPedSur <- do.call(rbind, dfnamePedSur)

#drop the newborns now
datOBp <- subset(datOB, age != 0)

```

```{r, echo=T}
# extract year info
datOBp$year <- as.numeric(substr(datOBp$admission, 1, 4))
datGYN$year <- as.numeric(substr(datGYN$admission, 1, 4))
datPED$year <- as.numeric(substr(datPED$admission, 1, 4))
datPedSur$year <- as.numeric(substr(datPedSur$admission, 1, 4))

# extract month info
datOBp$month <- as.numeric(substr(datOBp$admission, 6, 7))
datGYN$month <- as.numeric(substr(datGYN$admission, 6, 7))
datPED$month <- as.numeric(substr(datPED$admission, 6, 7))
datPedSur$month <- as.numeric(substr(datPedSur$admission, 6, 7))

```

```{r, echo=T}
# export dataframes as csv files
write.csv(datGYN,"~/Documents/R/Research/Shandong/Data/allgyn.csv", row.names = F)
write.csv(datOBp,"~/Documents/R/Research/Shandong/Data/allob.csv", row.names = F)
write.csv(datPED,"~/Documents/R/Research/Shandong/Data/allped.csv", row.names = F)
write.csv(datPedSur,"~/Documents/R/Research/Shandong/Data/allpedsur.csv", row.names = F)

```


***

### Appendix

```{r,ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE, tidy=TRUE, tidy.opts=list(width.cutoff=60)}
```